
services: # definovanie sluzieb/sluzby, ktore sa budu spustat v containeri
  alfa: # nazov sluzby, ktora sa bude spustat v containeri
    build: # definovanie build fazy, kde sa definuje cesta k Dockerfile, a target, ktory sa ma vykonat
      context: . # Path pre dockerfile
      target: development # Target pre dockerfile
    volumes: # mapovanie adresara z hosta do containera, 
      - ./:/app # mapovanie adresara z hosta do containera
      - /app/node_modules # vylucenie node_modules cez ojeb ( docker bude ignorovat specifickejsiu cestu)
    ports:
      - 3000:3000 # port forwarding z hosta na container (host:container)
    command: npm run dev  

#host - pocitac na ktorom bezi docker

#container - docker container
